spring.application.name=chenile-scheduler-sample
spring.profiles.default=jdbc
spring.jackson.serialization.indent-output=true
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:chenile-scheduler-schema.sql,classpath:chenile-scheduler-work-schema.sql
management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health,info
