server.port=0
chenile.scheduler.json.package=
scheduler.sample.worker.enabled=true
scheduler.sample.worker.run-once=false
scheduler.sample.worker.poll-interval-millis=5000
scheduler.sample.worker.lock-seconds=120
