server.port=${SERVER_PORT:18080}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:55432/scheduler}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:scheduler}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:scheduler}
chenile.scheduler.launcher.default=local
chenile.scheduler.store.type=jdbc
