chenile.service.json.package=classpath*:org/chenile/**/service/*.json
chenile.event.json.package=
chenile.scheduler.json.package=classpath*:org/chenile/samples/scheduler/jobs/*.json
chenile.interceptors.path=org/chenile/core/chenile-core.xml
chenile.monolith.name=scheduler-sample
chenile.base.url=http://localhost:18080
chenile.pre.processors=populateContextContainer
chenile.post.processors=
