<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>4.0.6</version>
        <relativePath/>
    </parent>

    <groupId>org.chenile.samples.securityauth</groupId>
    <artifactId>security-auth-sample-parent</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>Chenile Security Auth Sample</name>

    <properties>
        <java.version>25</java.version>
        <chenile.security.version>2.1.26</chenile.security.version>
        <spring-cloud.version>2025.1.2</spring-cloud.version>
    </properties>

    <modules>
        <module>auth-implementation</module>
        <module>auth-server-app</module>
        <module>gateway-app</module>
        <module>service-a</module>
        <module>service-b</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.chenile</groupId>
                <artifactId>chenile-security-auth-core</artifactId>
                <version>${chenile.security.version}</version>
            </dependency>
            <dependency>
                <groupId>org.chenile</groupId>
                <artifactId>chenile-security-auth-server</artifactId>
                <version>${chenile.security.version}</version>
            </dependency>
            <dependency>
                <groupId>org.chenile</groupId>
                <artifactId>chenile-security-gateway</artifactId>
                <version>${chenile.security.version}</version>
            </dependency>
            <dependency>
                <groupId>org.chenile</groupId>
                <artifactId>chenile-security-starter-resource-server</artifactId>
                <version>${chenile.security.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
