chenile.service.name=bulk-upload-process-sample
chenile.service.version=0.0.1-SNAPSHOT
chenile.module.name=bulk-upload-process-sample
chenile.base.url=http://localhost:8095
chenile.service.json.package=
chenile.event.json.package=
chenile.interceptors.path=org/chenile/samples/bulkupload/interceptors.xml
chenile.pre.processors=
chenile.post.processors=
