apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: bulk-upload-postgres-auth
  namespace: chenile-bulk-upload
spec:
  secretTargetRef:
    - parameter: userName
      name: bulk-upload-secret
      key: POSTGRES_USER
    - parameter: password
      name: bulk-upload-secret
      key: POSTGRES_PASSWORD
