server:
  port: 8082

spring:
  application:
    name: service-b

chenile:
  security:
    jwt:
      issuer-base: ${CHENILE_SECURITY_JWT_ISSUER_BASE:http://localhost:9000}
      jwk-base-uri: ${CHENILE_SECURITY_JWT_JWK_BASE_URI:http://localhost:9000}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
