apiVersion: v1
kind: ServiceAccount
metadata:
  name: bulk-upload-api
  namespace: chenile-bulk-upload
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: bulk-upload-worker
  namespace: chenile-bulk-upload
