apiVersion: v1
kind: Secret
metadata:
  name: scheduler-sample-secret
  namespace: chenile-scheduler-sample
type: Opaque
stringData:
  SPRING_DATASOURCE_PASSWORD: "change-me"
  POSTGRES_PASSWORD: "change-me"
  POSTGRES_CONNECTION_STRING: "postgresql://scheduler:change-me@scheduler-postgres.chenile-scheduler-sample.svc.cluster.local:5432/scheduler?sslmode=disable"
