apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduler-sample
  namespace: chenile-scheduler-sample
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scheduled-report-worker
  namespace: chenile-scheduler-sample
