apiVersion: v1
kind: Service
metadata:
  name: scheduler-sample
  namespace: chenile-scheduler-sample
spec:
  selector:
    app.kubernetes.io/name: scheduler-sample
  ports:
    - name: http
      port: 8080
      targetPort: http
