chenile.service.json.package=
chenile.event.json.package=
chenile.interceptors.path=org/chenile/core/chenile-core.xml
chenile.module.name=service-registry-sample-registry
chenile.base.url=${CHENILE_BASE_URL:http://localhost:8090}
chenile.pre.processors=
chenile.post.processors=
chenile.copy.headers.strategy=
